# Trabajando con opciones

In [3]:
#importar los paquetes que se van a usar
import pandas as pd
import pandas_datareader.data as web
import numpy as np
import datetime
import matplotlib.pyplot as plt
import scipy.stats as stats
import seaborn as sns
%matplotlib inline
#algunas opciones para Pandas
pd.set_option('display.notebook_repr_html', True)
pd.set_option('display.max_columns', 6)
pd.set_option('display.max_rows', 10)
pd.set_option('display.width', 78)
pd.set_option('precision', 3)

Usando el paquete `pandas_datareader` también podemos descargar datos de opciones. Por ejemplo, descarguemos los datos de las opciones que ofrece Apple a la fecha

In [21]:
aapl = web.Options('AAPL', 'yahoo')
aapl_opt = aapl.get_all_data().reset_index()
aapl_opt

,Strike,Expiry,Type,...,Quote_Time,Last_Trade_Date,JSON
0,2.5,2018-02-16,call,...,2018-02-07 20:44:01,2018-01-31 14:30:00,"{'contractSymbol': 'AAPL180216C00002500', 'str..."
1,2.5,2018-02-16,put,...,2018-02-07 20:44:01,2018-01-20 04:44:39,"{'contractSymbol': 'AAPL180216P00002500', 'str..."
2,2.5,2018-03-16,put,...,2018-02-07 20:44:02,2018-02-03 04:52:03,"{'contractSymbol': 'AAPL180316P00002500', 'str..."
3,2.5,2018-04-20,call,...,2018-02-07 20:35:49,2017-11-28 16:24:01,"{'contractSymbol': 'AAPL180420C00002500', 'str..."
4,2.5,2018-04-20,put,...,2018-02-07 20:35:49,2017-09-23 03:55:28,"{'contractSymbol': 'AAPL180420P00002500', 'str..."
...,...,...,...,...,...,...,...
966,320.0,2018-04-20,call,...,2018-02-07 20:35:49,2018-02-07 14:32:34,"{'contractSymbol': 'AAPL180420C00320000', 'str..."
967,325.0,2018-07-20,put,...,2018-02-07 20:35:49,2018-01-13 04:45:00,"{'contractSymbol': 'AAPL180720P00325000', 'str..."
968,340.0,2018-07-20,call,...,2018-02-07 20:35:49,2018-01-26 19:12:28,"{'contractSymbol': 'AAPL180720C00340000', 'str..."
969,345.0,2018-02-16,call,...,2018-02-07 20:44:01,2018-01-24 14:35:46,"{'contractSymbol': 'AAPL180216C00345000', 'str..."
970,360.0,2018-03-16,call,...,2018-02-07 20:44:02,2018-01-27 04:50:54,"{'contractSymbol': 'AAPL180316C00360000', 'str..."

Una vez tenemos la información, podemos consultar de qué tipo son las opciones

In [22]:
aapl_opt.loc[:, 'Type']

0      call
1       put
2       put
3      call
4       put
       ...
966    call
967     put
968    call
969    call
970    call
Name: Type, Length: 971, dtype: object

o en que fecha expiran

In [25]:
aapl_opt.loc[:, 'Expiry']

0     2018-02-16
1     2018-02-16
2     2018-03-16
3     2018-04-20
4     2018-04-20
         ...
966   2018-04-20
967   2018-07-20
968   2018-07-20
969   2018-02-16
970   2018-03-16
Name: Expiry, Length: 971, dtype: datetime64[ns]

Por otra parte, podríamos querer consultar todas las opciones de compra (call) que expiran en cierta fecha (2018-03-16)

In [39]:
call03 = aapl_opt.loc[(aapl_opt.Expiry=='2018-03-16') & (aapl_opt.Type=='call')]
call03

,Strike,Expiry,Type,...,Quote_Time,Last_Trade_Date,JSON
111,100.0,2018-03-16,call,...,2018-02-07 20:44:02,2018-01-27 04:50:47,"{'contractSymbol': 'AAPL180316C00100000', 'str..."
156,115.0,2018-03-16,call,...,2018-02-07 20:44:02,2018-02-05 17:08:26,"{'contractSymbol': 'AAPL180316C00115000', 'str..."
172,120.0,2018-03-16,call,...,2018-02-07 20:44:02,2018-02-05 16:28:22,"{'contractSymbol': 'AAPL180316C00120000', 'str..."
190,125.0,2018-03-16,call,...,2018-02-07 20:44:02,2018-02-07 14:30:16,"{'contractSymbol': 'AAPL180316C00125000', 'str..."
209,130.0,2018-03-16,call,...,2018-02-07 20:44:02,2018-02-06 20:50:50,"{'contractSymbol': 'AAPL180316C00130000', 'str..."
...,...,...,...,...,...,...,...
901,245.0,2018-03-16,call,...,2018-02-07 20:44:02,2018-02-03 04:50:58,"{'contractSymbol': 'AAPL180316C00245000', 'str..."
924,255.0,2018-03-16,call,...,2018-02-07 20:44:02,2018-02-03 04:50:58,"{'contractSymbol': 'AAPL180316C00255000', 'str..."
944,270.0,2018-03-16,call,...,2018-02-07 20:44:02,2018-02-03 04:50:58,"{'contractSymbol': 'AAPL180316C00270000', 'str..."
959,300.0,2018-03-16,call,...,2018-02-07 20:44:02,2018-01-27 04:50:52,"{'contractSymbol': 'AAPL180316C00300000', 'str..."
970,360.0,2018-03-16,call,...,2018-02-07 20:44:02,2018-01-27 04:50:54,"{'contractSymbol': 'AAPL180316C00360000', 'str..."

In [40]:
(aapl_opt.Expiry=='2018-03-16') & (aapl_opt.Type=='call')

0      False
1      False
2      False
3      False
4      False
       ...
966    False
967    False
968    False
969    False
970     True
Length: 971, dtype: bool

<script>
  $(document).ready(function(){
    $('div.prompt').hide();
    $('div.back-to-top').hide();
    $('nav#menubar').hide();
    $('.breadcrumb').hide();
    $('.hidden-print').hide();
  });
</script>

<footer id="attribution" style="float:right; color:#808080; background:#fff;">
Created with Jupyter by Esteban Jiménez Rodríguez.
</footer>